name = "BifurcationKit"
uuid = "0f109fa4-8a5d-4b75-95aa-f515264e7665"
authors = ["Romain Veltz <rveltz@salk.edu>"]
version = "0.3.3"

[deps]
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
ArnoldiMethod = "0.0.4, 0.1, 0.2, 0.3, 0.4"
Arpack = "=0.5.3, 0.5"
BlockArrays = "0.14, 0.15, ^0.16"
DataStructures = "0.17, 0.18"
DocStringExtensions = "^0.8, ^0.9"
FastGaussQuadrature = "^0.4, ^0.5, 1"
ForwardDiff = "^0.10"
IterativeSolvers = "0.8.4, 0.8.5, ^0.9"
KrylovKit = "0.5.4, ^0.6, 0.7"
LinearMaps = "2.7, ^3.0"
OrdinaryDiffEq = "^6.33"
Parameters = "0.12.3"
RecipesBase = "1.0, 1.1"
RecursiveArrayTools = "^2.3, ^2.4, ^2.8, ^2.9, ^3"
Reexport = "1.2.2"
Requires = "1.1.2"
SciMLBase = "^1, ^2"
Setfield = "0.5.0, 0.7.0, 0.8.0, ^1.1"
StructArrays = "0.4, ^0.6"
julia = "1.5"

[extras]
AbstractDifferentiation = "c29ec348-61ec-40c8-8164-b8c60e9d9f3d"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "ForwardDiff", "OrdinaryDiffEq", "Random", "AbstractDifferentiation", "Zygote", "SciMLSensitivity", "ComponentArrays"]
