[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocThemeIndigo = "8bac0ac5-51bf-41f9-885e-2bf1ac2bec5f"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"

[compat]
Documenter = "0.24.3"
Setfield = "0.5.0, 0.7.0, 0.8.0"
